ui: mocha-bdd
browsers:
  - name: chrome
    version: -1..latest
  - name: safari
    version: -1..latest
  # TODO: put firefox back to latest once sauce has deployed updated selenium
  # see: https://twitter.com/saucelabs/status/750741932075323392
  - name: firefox
    version: -1..46
  - name: ie
    version: -1..latest
