language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  api_key:
    secure: DuF6Mqel1lvt6Dvx8t3y0jYgOgC6NW6aeFtv8eMv48mJqw4w/MF6BucfD94F9VY5QW1vhgkY1jRC6kK3bwd1Vn9PFPi0AdX+Zu6d/OpLr0d4vzhBHkx70UFB3ewsrYg2zwGKlpu3VTyMODbluw1nv3meLBLtxfr9xb1PJAAMq3I=
  on:
    tags: true
    branch: master
