sudo: false
language: node_js
node_js:
- '0.12'
- '0.10'
- iojs
script: gulp travis
before_deploy: gulp
deploy:
  provider: npm
  email: mike@cousins.io
  api_key:
    secure: VFkMN1RibccubM2NahCoVEZJCKuWe3WhPFD5hAizbh6vBeeR3WhW+utSjrs0kwiOsw3MgBwdHopnAYN/C2//jYnzCePyCSogoGRz2Vn3hDo+KZqo2T4PKBUpLfR3076Q2P9PIxcoQ1g0WX+Cmln6Qjhu5UcnZux9cnipfHZ6jRw=
  on:
    node: iojs
    tags: true
    all_branches: true
after_deploy: gulp browsers
env:
  global:
  - secure: SJVboTQgHqXU1UrY2zNkWzr9Gd75Qe8Uzyj7lCTK8C0P5Y9Jg+vE+bHOBKvehgXLmfrVGLZc93n6EilA52XWW0B6U3X6nPk/Pu9/fZRMK8AiyCLD0bfCgiPCikrNRdpp/1PHgbJyuaaYPlEhYE8SwmADGZk9UHFSPMlJQqDrQco=
  - secure: U92/0p44DjV4u9FFJno6Bc75hXJ6lMfRpRaCfcxv2LL0aIqwVTKH87Yw1r68YrTDgimdiGFnkuxp4z8yucqRc7kXyagwd8QD5uPU3T6kA+LokJ2yfaXr6OSy2lJhb5KUiRbJ45/ybc0mMI6VYUUxzMDOjwTPgt7Gv2SDMLaq8Rs=
