# speed up this build: http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

language: node_js
node_js:
- '0.10'
script: gulp travis
# build lib before deploy
before_depoly: gulp
# deploy to npm
deploy:
  provider: npm
  email: mike@cousins.io
  api_key:
    secure: gHhYjLHwFNd8uCkYQtyOk1uwRCpY0pzBzBc200+JJUxwKmXH9ZHiAKJGAx9/V/O5fwkXcl1NCz/+TSfBo/6gQz3lx1GUgnH0uazgPdaFeSAARiXK85aLp857rR9i8q9DLbGyQgWj07zdNen3Jmw7JU3tHBxNKYDtWXlTJFFcrCE=
  on:
    tags: true
    all_branches: true
# run browser tests after a deploy
after_deploy: gulp browsers
addons:
  sauce_connect: true
env:
  global:
    - secure: SJVboTQgHqXU1UrY2zNkWzr9Gd75Qe8Uzyj7lCTK8C0P5Y9Jg+vE+bHOBKvehgXLmfrVGLZc93n6EilA52XWW0B6U3X6nPk/Pu9/fZRMK8AiyCLD0bfCgiPCikrNRdpp/1PHgbJyuaaYPlEhYE8SwmADGZk9UHFSPMlJQqDrQco=
    - secure: U92/0p44DjV4u9FFJno6Bc75hXJ6lMfRpRaCfcxv2LL0aIqwVTKH87Yw1r68YrTDgimdiGFnkuxp4z8yucqRc7kXyagwd8QD5uPU3T6kA+LokJ2yfaXr6OSy2lJhb5KUiRbJ45/ybc0mMI6VYUUxzMDOjwTPgt7Gv2SDMLaq8Rs=
