ui: mocha-bdd
browsers:
  - name: chrome
    version: 39..latest
  - name: safari
    version: 6..latest
  - name: firefox
    version: 34..latest
  - name: ie
    version: 9..latest
  - name: iphone
    version: 7.1..latest
  - name: android
    version: 4.3..latest
browserify:
  - transform: coffeeify
  - transform: brfs
  - options:
      extensions:
        - .coffee
