ui: mocha-bdd
browsers:
  - name: chrome
    version: 38..latest
  - name: safari
    version: 6..latest
  - name: firefox
    version: 33..latest
  - name: ie
    version: 9..latest
  - name: iphone
    version: latest
  - name: android
    version: latest
browserify:
  - require: should
    entry: true
  - transform: coffeeify
  - transform: brfs
  - options:
      extensions:
        - .coffee
      
