ui: mocha-bdd
browsers:
- name: chrome
    version: 42..latest
  - name: safari
    version: 7..latest
  - name: firefox
    version: 38..latest
  - name: ie
    version: 10..latest
  - name: opera
    version: latest
browserify:
  - transform: coffeeify
  - transform: brfs
  - options:
      extensions:
        - .coffee
